#!/usr/bin/env python3
"""
On-Device Merchant Classifier Training Script
Trains a Log-Linear Softmax Model with character n-grams and word tokens
for classifying Indian merchant names and transaction descriptions into 14 expense categories.
Exports model weights directly to JSON for ultra-fast on-device native Kotlin inference.
"""

import json
import os
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import FeatureUnion

CATEGORIES = [
    "FOOD",
    "GROCERIES",
    "SHOPPING",
    "TRANSPORT",
    "BILLS_UTILITIES",
    "ENTERTAINMENT",
    "HEALTHCARE",
    "INVESTMENT",
    "SALARY_INCOME",
    "TRANSFERS",
    "FEES_CHARGES",
    "EDUCATION",
    "PERSONAL",
    "OTHERS"
]

# Comprehensive training dataset covering real-world Indian merchant names, South Indian restaurants,
# kirana stores, supermarkets, pharmacies, transport outlets, AI/cloud subscriptions, P2P transfers, etc.
DATASET = [
    # FOOD (Restaurants, Cafes, Messes, Bakeries, Street Food, Tea Stalls)
    ("Sharma Sweets House", "FOOD"),
    ("Chai Point Express", "FOOD"),
    ("Amma Canteen", "FOOD"),
    ("Bawarchi Biryani Point", "FOOD"),
    ("Madras Cafe & Tiffin", "FOOD"),
    ("Gupta Dosa Corner", "FOOD"),
    ("Hot & Spicy Fast Food", "FOOD"),
    ("Kathi Roll Junction", "FOOD"),
    ("Gokul Chaat Bhandar", "FOOD"),
    ("Haldiram Sweets & Snacks", "FOOD"),
    ("Saravana Bhavan Hotel", "FOOD"),
    ("Paradise Food Court", "FOOD"),
    ("Annapurna Mess & Meals", "FOOD"),
    ("Sri Krishna Sweets", "FOOD"),
    ("Kwality Ice Cream Parlour", "FOOD"),
    ("Fresh Juice Center", "FOOD"),
    ("Bakingo Cake Bakery", "FOOD"),
    ("Theobroma Patisserie", "FOOD"),
    ("Burger House & Shakes", "FOOD"),
    ("Tandoor Hut Restro", "FOOD"),
    ("Bhojanalaya & Thali", "FOOD"),
    ("Punjab Dhaba Highway", "FOOD"),
    ("Coffee Day Lounge", "FOOD"),
    ("Star Cafe Bistro", "FOOD"),
    ("Kolkata Rolls & Kebabs", "FOOD"),
    ("Momo Nation Corner", "FOOD"),
    ("Waffle & Shake Bar", "FOOD"),
    ("Chai Sutta Bar Corner", "FOOD"),
    ("Chaayos Chai & Snacks", "FOOD"),
    ("Blue Tokai Coffee Roasters", "FOOD"),
    ("Third Wave Coffee Roasters", "FOOD"),
    ("Third Wave Coffee House", "FOOD"),
    ("Barbeque Nation Dining", "FOOD"),
    ("Bikanervala Foods & Sweets", "FOOD"),
    ("A2B Adyar Ananda Bhavan", "FOOD"),
    ("Meghana Foods Singasandra", "FOOD"),
    ("Meghana Biryani House", "FOOD"),
    ("Dominos Pizza India", "FOOD"),
    ("Pizza Hut Express", "FOOD"),
    ("Burger King Whopper", "FOOD"),
    ("KFC Fried Chicken", "FOOD"),
    ("Subway Sandwiches & Salads", "FOOD"),
    ("Starbucks Coffee Shop", "FOOD"),
    ("Taco Bell Mexican Foods", "FOOD"),
    ("Faasos Gourmet Wraps", "FOOD"),
    ("Behrouz Royal Biryani", "FOOD"),
    ("Ovenstory Artisanal Pizza", "FOOD"),
    ("EatClub Food Delivery", "FOOD"),
    ("Box8 Desi Meals Box", "FOOD"),
    ("Freshmenu Gourmet Food", "FOOD"),
    ("Jolly Cafe & Beverages", "FOOD"),
    ("Mohans Hot N Chat", "FOOD"),
    ("Mohans Hot N Chat Restaurant", "FOOD"),
    ("Ajnabi Mithaai Prime", "FOOD"),
    ("Hotel Olympic Fast Food", "FOOD"),
    ("Aaram Buhari Hotel", "FOOD"),
    ("Sangeetha Veg Restaurant RA Puram", "FOOD"),
    ("Sangeetha Veg Restaurant", "FOOD"),
    ("Gastronomic Foods", "FOOD"),
    ("Chai Sultan Tea Stall", "FOOD"),
    ("Madras Melody Restaurants", "FOOD"),
    ("Madras Melody Restaurants LLP Geetham", "FOOD"),
    ("Manoj Bhavan Restaurant", "FOOD"),
    ("Kanchipuram Kaapi Coffee", "FOOD"),
    ("Kiran Tea Stall Snacks", "FOOD"),
    ("KTDC Rain Drops Hotel", "FOOD"),
    ("Lakshmi Narayan Bhavan", "FOOD"),
    ("Les Amis French Cafe", "FOOD"),
    ("M S Tantea Canteen", "FOOD"),
    ("Murugan Idli Shop", "FOOD"),
    ("Packiyaraj Mess Daily Meals", "FOOD"),
    ("Pearltri Foods Pvt Ltd", "FOOD"),
    ("RRFoods T Nagar Dining", "FOOD"),
    ("S L V Iyangar Bakery", "FOOD"),
    ("SASGHPL Sree Annapoorna", "FOOD"),
    ("Sree Akshaya Veg Restaurant", "FOOD"),
    ("Sree Annapoorna Sree Gowrishankar", "FOOD"),
    ("Sri Bhagya Veg Hotel", "FOOD"),
    ("Sri Selva Snacks Corner", "FOOD"),
    ("Sri Senthur Muruga Hotel", "FOOD"),
    ("Sri Vanitha Bakes & Sweets", "FOOD"),
    ("SS Hyderabad Biryani House", "FOOD"),
    ("SS Hyderabad Briyani Express", "FOOD"),
    ("Sri Adyar Saravana Bakery", "FOOD"),
    ("The Juice Heaven Fresh Juices", "FOOD"),
    ("Theobroma Foods Pvt Ltd", "FOOD"),
    ("TN CHN T Nagar KFC Outlet", "FOOD"),
    ("Udupi Mahaganapathi Mess", "FOOD"),
    ("Waycup Coffee Roasters", "FOOD"),
    ("West Mambalam Chips & Snacks", "FOOD"),
    ("Zaitoon Nungambakkam Restaurant", "FOOD"),
    ("Zomato Limited Food Order", "FOOD"),
    ("Swiggy Limited Food Delivery", "FOOD"),
    ("Swiggy Dineout Restaurant Bill", "FOOD"),
    ("McDonalds Fast Food Burger", "FOOD"),
    ("JB Foods A Pet Canteen", "FOOD"),
    ("Kailash Parbat Cuisine", "FOOD"),
    ("Kakada Ramprasad Sweets", "FOOD"),
    ("Karur Ghee Store Sweets", "FOOD"),
    ("Naturals Ice Cream", "FOOD"),
    ("Baskin Robbins Ice Creams", "FOOD"),

    # GROCERIES (Supermarkets, Kirana Stores, Fresh Produce, Dairy, Quick Commerce)
    ("Gupta Kirana Store", "GROCERIES"),
    ("Daily Needs Supermarket", "GROCERIES"),
    ("Fresh Vegetable Mart", "GROCERIES"),
    ("Balaji Provision Stores", "GROCERIES"),
    ("City Super Market", "GROCERIES"),
    ("Shree Ram Supermarket", "GROCERIES"),
    ("Kisan Mandi Fruits & Veg", "GROCERIES"),
    ("Nature Fresh Dairy & Milk", "GROCERIES"),
    ("Aman Organic Grocery", "GROCERIES"),
    ("Shakti Departmental Store", "GROCERIES"),
    ("Green Farm Produce Mart", "GROCERIES"),
    ("Local Kirana & General Store", "GROCERIES"),
    ("Smart Point Grocery Outlet", "GROCERIES"),
    ("Reliance Fresh Produce", "GROCERIES"),
    ("More Supermarket Provisions", "GROCERIES"),
    ("Spencer Retail Grocery", "GROCERIES"),
    ("Blinkit Commerce Pvt Ltd", "GROCERIES"),
    ("Zepto Instant Grocery", "GROCERIES"),
    ("Zepto Marketplace Grocery", "GROCERIES"),
    ("Swiggy Instamart Grocery", "GROCERIES"),
    ("BigBasket Online Grocery", "GROCERIES"),
    ("BB Daily Milk Subscription", "GROCERIES"),
    ("BB Instant Smart Store", "GROCERIES"),
    ("Dunzo Daily Provisions", "GROCERIES"),
    ("Country Delight Pure Milk", "GROCERIES"),
    ("Milkbasket Morning Grocery", "GROCERIES"),
    ("DMart Supermarket Ready", "GROCERIES"),
    ("JioMart Smart Bazaar Grocery", "GROCERIES"),
    ("Ratnadeep Supermarket Grocery", "GROCERIES"),
    ("Nature Basket Artisanal Gourmet", "GROCERIES"),
    ("Licious Fresh Meat & Eggs", "GROCERIES"),
    ("FreshToHome Fish & Chicken", "GROCERIES"),
    ("Meatigo Gourmet Meat Cuts", "GROCERIES"),
    ("Prabhu Super Market Provisions", "GROCERIES"),
    ("KPN Farm Fresh Produce", "GROCERIES"),
    ("KPN Farm Fresh Private Limited", "GROCERIES"),
    ("Smart Bazaar Supermarket", "GROCERIES"),
    ("Pavithra Green Fresh Produce", "GROCERIES"),
    ("Ponnys Stores Kirana Provisions", "GROCERIES"),
    ("Raam Nuts And Groceries", "GROCERIES"),
    ("Kumaran Stores General Kirana", "GROCERIES"),
    ("Jayaram Store Grocery", "GROCERIES"),
    ("MSA Mini Super Market", "GROCERIES"),
    ("Thirumalai Fruits Stall", "GROCERIES"),
    ("Thirumurugan Store General Grocery", "GROCERIES"),
    ("Shree Kumaran Departmental Stores", "GROCERIES"),
    ("Patanjali Arogya Kendra Grocery", "GROCERIES"),
    ("Akshayakalpa Organic Milk", "GROCERIES"),

    # SHOPPING (E-Commerce, Apparel, Textiles, Electronics, Hardware, Furniture, Flowers)
    ("Amazon India Shopping Order", "SHOPPING"),
    ("WWW Amazon In Retail Order", "SHOPPING"),
    ("Flipkart Internet Pvt Ltd", "SHOPPING"),
    ("Myntra Designs Fashion", "SHOPPING"),
    ("Ajio Reliance Fashion Trends", "SHOPPING"),
    ("Meesho Technologies Online", "SHOPPING"),
    ("Tata CLiQ Luxury Shopping", "SHOPPING"),
    ("Nykaa E-Retail Cosmetics", "SHOPPING"),
    ("Purplle Beauty & Personal", "SHOPPING"),
    ("Zudio A Unit of Trent Retail", "SHOPPING"),
    ("The Chennai Silks Textiles", "SHOPPING"),
    ("Ramraj Cotton Dhotis & Shirts", "SHOPPING"),
    ("RMR Textiles Sarees", "SHOPPING"),
    ("Metro Handlooms Silk Sarees", "SHOPPING"),
    ("Saravana Stores Elite Textiles", "SHOPPING"),
    ("Legend Saravana Mega Shopping Mall", "SHOPPING"),
    ("Lenskart Eyewear Solutions", "SHOPPING"),
    ("Lenskart PayU Optical Store", "SHOPPING"),
    ("Vitco Shoe Complex Footwear", "SHOPPING"),
    ("Viveka Aquarium Pets & Supplies", "SHOPPING"),
    ("Vaibhave Shoppe Gift Store", "SHOPPING"),
    ("WWW OLX IN Classifieds", "SHOPPING"),
    ("New Pandian Electronics", "SHOPPING"),
    ("S K Electronics Mobiles & TV", "SHOPPING"),
    ("SK Electronics Home Appliances", "SHOPPING"),
    ("Rajam Electronics and Electricals", "SHOPPING"),
    ("K M T Hardwares Tools & Paints", "SHOPPING"),
    ("Padmaraja Hardware Electricals", "SHOPPING"),
    ("Monish Ali Flowers & Bouquets", "SHOPPING"),
    ("Mr Lock Smith Keys & Locks", "SHOPPING"),
    ("Ever Shine Furniture Home Decor", "SHOPPING"),
    ("Jayam Enterprises Retail", "SHOPPING"),
    ("Sri Mookambika Enterprises Retail", "SHOPPING"),
    ("Sri Raghavendra Enterprises Hardware", "SHOPPING"),
    ("Sri Venkatramana Enterprises Shopping", "SHOPPING"),
    ("Sri Meenakshi Agencies Retail", "SHOPPING"),
    ("KP Selvam Agency Retail Store", "SHOPPING"),
    ("Maruthi Agency Wholesale Retail", "SHOPPING"),
    ("Reliance Retail Limited Shopping", "SHOPPING"),
    ("Max Retail Apparel Fashion", "SHOPPING"),
    ("Zara Clothing India Store", "SHOPPING"),
    ("H&M Hennes & Mauritz Retail", "SHOPPING"),
    ("Uniqlo India Garments", "SHOPPING"),
    ("Decathlon Sports India Goods", "SHOPPING"),
    ("Shoppers Stop Departmental Mall", "SHOPPING"),
    ("Westside Trent Lifestyle", "SHOPPING"),
    ("Pantaloons Aditya Birla Fashion", "SHOPPING"),
    ("Croma Infiniti Retail Electronics", "SHOPPING"),
    ("Reliance Digital Megastore", "SHOPPING"),
    ("Vijay Sales Electronics", "SHOPPING"),
    ("Poorvika Mobiles Pvt Ltd", "SHOPPING"),
    ("Sangeetha Mobiles Pvt Ltd", "SHOPPING"),
    ("Titan Watches & Eyeplus", "SHOPPING"),
    ("Tanishq Jewellery Titan", "SHOPPING"),
    ("Kalyan Jewellers Gold & Diamond", "SHOPPING"),
    ("Malabar Gold & Diamonds", "SHOPPING"),
    ("IKEA India Furniture & Home", "SHOPPING"),
    ("Pepperfry Wooden Furniture", "SHOPPING"),
    ("Urban Ladder Home Furniture", "SHOPPING"),
    ("FirstCry Brainbees Solutions Kids", "SHOPPING"),

    # TRANSPORT (Cabs, Autos, Fuel Stations, Trains, Flights, Bus Booking)
    ("Ramesh Cabs Travels", "TRANSPORT"),
    ("Indian Oil Petrol Bunk", "TRANSPORT"),
    ("Ather EV Charging Station", "TRANSPORT"),
    ("Sharma Taxi & Car Rental", "TRANSPORT"),
    ("Toll Plaza NHAI Fastag", "TRANSPORT"),
    ("Metro Station Smart Card", "TRANSPORT"),
    ("IRCTC Railway Ticket Booking", "TRANSPORT"),
    ("Bharat Petroleum Pump", "TRANSPORT"),
    ("Hindustan Petroleum Station", "TRANSPORT"),
    ("Shell Fuel & Lubricants", "TRANSPORT"),
    ("Nayara Fuel Station Pump", "TRANSPORT"),
    ("RedBus India Private Limited", "TRANSPORT"),
    ("RedBus IN Bus Ticket Booking", "TRANSPORT"),
    ("AbhiBus Bus Tickets Online", "TRANSPORT"),
    ("Rapido Bike Taxi & Auto", "TRANSPORT"),
    ("Roppen Transportation Rapido", "TRANSPORT"),
    ("Uber India Systems Private Limited", "TRANSPORT"),
    ("Ola Cabs ANI Technologies", "TRANSPORT"),
    ("Namma Yatri Auto Ride", "TRANSPORT"),
    ("BluSmart Electric Mobility Cabs", "TRANSPORT"),
    ("MakeMyTrip Flight & Hotel Booking", "TRANSPORT"),
    ("Goibibo Travel Bookings", "TRANSPORT"),
    ("EaseMyTrip Flight Tickets", "TRANSPORT"),
    ("Cleartrip Air Tickets", "TRANSPORT"),
    ("IndiGo Airlines InterGlobe", "TRANSPORT"),
    ("Air India Flight Booking", "TRANSPORT"),
    ("Vistara Airlines TATA SIA", "TRANSPORT"),
    ("Akasa Air Flight Tickets", "TRANSPORT"),
    ("SpiceJet Airlines Flight", "TRANSPORT"),
    ("State Transport Corporation Bus", "TRANSPORT"),
    ("WSG New Bus Karaikudi Travels", "TRANSPORT"),
    ("Jai Autos Bajaj Two Wheeler Service", "TRANSPORT"),
    ("Balakrishna Automobiles Garage", "TRANSPORT"),
    ("MGK Motor Cycles Service", "TRANSPORT"),
    ("Sathya Auto Garage Works", "TRANSPORT"),
    ("Pump 2 Saravanan S Fuel Station", "TRANSPORT"),
    ("Pump 6 Sakthi Auto Fuels Petrol", "TRANSPORT"),
    ("Sri Devi Petrol Station HPCL", "TRANSPORT"),
    ("Uma Service Station Bharat Petroleum", "TRANSPORT"),
    ("Namma Metro Smart Card Recharge", "TRANSPORT"),
    ("DMRC Delhi Metro Rail Card", "TRANSPORT"),
    ("Airport Parking Lot Fee", "TRANSPORT"),
    ("Park+ FASTag Recharge & Valet", "TRANSPORT"),

    # BILLS_UTILITIES (Electricity, Gas, Water, Telecom, Cloud & AI Subscriptions)
    ("BESCOM Bangalore Electricity Bill", "BILLS_UTILITIES"),
    ("Tata Power DDL Electricity Bill", "BILLS_UTILITIES"),
    ("TANGEDCO Tamil Nadu Electricity", "BILLS_UTILITIES"),
    ("Mahanagar Gas Piped LPG Bill", "BILLS_UTILITIES"),
    ("Indraprastha Gas IGL Bill", "BILLS_UTILITIES"),
    ("Indane LPG Cylinder Booking", "BILLS_UTILITIES"),
    ("Bharat Gas Cylinder Payment", "BILLS_UTILITIES"),
    ("HP Gas LPG Cylinder Booking", "BILLS_UTILITIES"),
    ("Delhi Jal Board Water Bill", "BILLS_UTILITIES"),
    ("BWSSB Water Supply Bill", "BILLS_UTILITIES"),
    ("Airtel Fiber Broadband Bill", "BILLS_UTILITIES"),
    ("ACT Fibernet Internet Bill", "BILLS_UTILITIES"),
    ("Tata Play DTH Recharge Bill", "BILLS_UTILITIES"),
    ("Dish TV DTH Recharge Bill", "BILLS_UTILITIES"),
    ("Sun Direct DTH Subscription", "BILLS_UTILITIES"),
    ("JIO Prepaid Recharge Plans", "BILLS_UTILITIES"),
    ("JIO Postpaid Mobile Bill", "BILLS_UTILITIES"),
    ("MyJio Mobile Recharge Payment", "BILLS_UTILITIES"),
    ("Jeeva Telecom Services Recharge", "BILLS_UTILITIES"),
    ("NoBroker Technologies Maintenance", "BILLS_UTILITIES"),
    ("Google India Digital Services BBPS", "BILLS_UTILITIES"),
    ("Google Cloud Platform Billing", "BILLS_UTILITIES"),
    ("UPA_Google Cloud Cloud Compute", "BILLS_UTILITIES"),
    ("Oracle Singapore Cloud Services", "BILLS_UTILITIES"),
    ("DeepSeek AI API Subscription", "BILLS_UTILITIES"),
    ("Anthropic Claude API Subscription", "BILLS_UTILITIES"),
    ("OpenAI ChatGPT Plus Subscription", "BILLS_UTILITIES"),
    ("GitHub Copilot Developer Subscription", "BILLS_UTILITIES"),
    ("Cursor AI Pro Subscription", "BILLS_UTILITIES"),
    ("V V Water Pool Technologies", "BILLS_UTILITIES"),
    ("One Sigma Technologies Hosting", "BILLS_UTILITIES"),
    ("BillDesk Payment Gateway Utility", "BILLS_UTILITIES"),
    ("BBPS National Electricity Portal", "BILLS_UTILITIES"),
    ("MyGate Apartment Maintenance Fee", "BILLS_UTILITIES"),

    # ENTERTAINMENT (Movies, OTT, Gaming, Sports, Music)
    ("PVR Cinemas Movie Tickets", "ENTERTAINMENT"),
    ("Inox Leisure Cinema Hall", "ENTERTAINMENT"),
    ("Cinepolis Multiplex Cinema", "ENTERTAINMENT"),
    ("BookMyShow Movie & Concert Tickets", "ENTERTAINMENT"),
    ("Paytm Insider Live Event Show", "ENTERTAINMENT"),
    ("Netflix Entertainment Subscription", "ENTERTAINMENT"),
    ("Amazon Prime Video OTT Media", "ENTERTAINMENT"),
    ("Disney Hotstar OTT Subscription", "ENTERTAINMENT"),
    ("SonyLIV Sony Pictures OTT", "ENTERTAINMENT"),
    ("Zee5 Entertainment Media OTT", "ENTERTAINMENT"),
    ("Spotify Premium Music Streaming", "ENTERTAINMENT"),
    ("Apple Music Streaming Subscription", "ENTERTAINMENT"),
    ("YouTube Premium Video Ad-Free", "ENTERTAINMENT"),
    ("UPA_Sun TV Network Limited OTT", "ENTERTAINMENT"),
    ("Valve Corporation Steam Game Store", "ENTERTAINMENT"),
    ("PlayStation Network PSN Games", "ENTERTAINMENT"),
    ("Xbox Game Pass Microsoft Gaming", "ENTERTAINMENT"),
    ("Ticket 9 Event Show Tickets", "ENTERTAINMENT"),
    ("Unipex Sportsbiz Turf & Court", "ENTERTAINMENT"),
    ("Smaaash Gaming & Bowling Arcade", "ENTERTAINMENT"),
    ("Timezone Arcade Bowling Games", "ENTERTAINMENT"),
    ("Wonderla Amusement Water Park", "ENTERTAINMENT"),

    # HEALTHCARE (Hospitals, Clinics, Pharmacies, Labs, Diagnostic Centers)
    ("Tata 1mg Healthcare Pharmacy", "HEALTHCARE"),
    ("Apollo Pharmacy 24/7 Meds", "HEALTHCARE"),
    ("Apollo 24|7 Health Consultation", "HEALTHCARE"),
    ("MedPlus Pharmacy & Chemist", "HEALTHCARE"),
    ("Netmeds Marketplace Pharmacy", "HEALTHCARE"),
    ("PharmEasy Medicine Home Delivery", "HEALTHCARE"),
    ("Practo Healthcare Doctor Consult", "HEALTHCARE"),
    ("Dr Lal Pathlabs Blood Tests", "HEALTHCARE"),
    ("Metropolis Healthcare Diagnostics", "HEALTHCARE"),
    ("Thyrocare Diagnostic Labs", "HEALTHCARE"),
    ("SRL Diagnostics Health Check", "HEALTHCARE"),
    ("Lakshmi Hospital Care Center", "HEALTHCARE"),
    ("Lakshmi Pharmacy Medicine Store", "HEALTHCARE"),
    ("Lakshmimmedical Pharmacy Shop", "HEALTHCARE"),
    ("SRM Prime Hospital Care", "HEALTHCARE"),
    ("Suba Medicals Druggist Store", "HEALTHCARE"),
    ("Jain Medicals Chemist Shop", "HEALTHCARE"),
    ("Jaya Medical Chemist & Druggist", "HEALTHCARE"),
    ("West Mambalam Pharmacy Meds", "HEALTHCARE"),
    ("Max Super Speciality Hospital", "HEALTHCARE"),
    ("Fortis Hospital Healthcare", "HEALTHCARE"),
    ("Manipal Hospital Medical Care", "HEALTHCARE"),
    ("Dental Care Clinic Root Canal", "HEALTHCARE"),
    ("Eye Hospital Cataract Lasik Clinic", "HEALTHCARE"),

    # INVESTMENT (Mutual Funds, Demat, Stocks, Broking, Fixed Deposits)
    ("Groww Invest Tech Private Limited", "INVESTMENT"),
    ("Groww Investment SIP Mandate", "INVESTMENT"),
    ("GROWW INVEST TECH PR IMPS", "INVESTMENT"),
    ("Zerodha Broking Limited Demat", "INVESTMENT"),
    ("Rainmatter Technology Pvt Ltd", "INVESTMENT"),
    ("Upstox RKSV Securities Trading", "INVESTMENT"),
    ("Angel One Broking Demat Account", "INVESTMENT"),
    ("ICICI Direct Share Trading", "INVESTMENT"),
    ("HDFC Securities Stock Demat", "INVESTMENT"),
    ("Kotak Securities Share Broking", "INVESTMENT"),
    ("Motilal Oswal Financial Services", "INVESTMENT"),
    ("Paytm Money Mutual Fund SIP", "INVESTMENT"),
    ("INDmoney US Stocks & Mutual Funds", "INVESTMENT"),
    ("Kuvera Wealth Investment Goal", "INVESTMENT"),
    ("Smallcase Technologies Basket", "INVESTMENT"),
    ("Shriram Insight Share Broking", "INVESTMENT"),
    ("Shriram Finance Limited Deposit", "INVESTMENT"),
    ("shriramfinance camspay deposit", "INVESTMENT"),
    ("NPS National Pension System Trust", "INVESTMENT"),
    ("Sovereign Gold Bond RBI Invest", "INVESTMENT"),

    # PERSONAL (Salons, Spas, Grooming, Fitness, Gyms)
    ("Urban Company Home Salon & Spa", "PERSONAL"),
    ("Looks Unisex Hair Salon & Spa", "PERSONAL"),
    ("Looks Unisex Hair Parlour", "PERSONAL"),
    ("Ayur Care Spa & Massage", "PERSONAL"),
    ("Grooming Lounge Mens Barber", "PERSONAL"),
    ("Grooming Salon Barber Shop", "PERSONAL"),
    ("Mens Barber Haircut Studio", "PERSONAL"),
    ("Toni & Guy Hair Salon", "PERSONAL"),
    ("Naturals Beauty Salon Hair", "PERSONAL"),
    ("Green Trends Unisex Hair Style", "PERSONAL"),
    ("Enrich Beauty Salon Haircut", "PERSONAL"),
    ("Geetanjali Salon Luxury Hair", "PERSONAL"),
    ("Jawed Habib Hair & Beauty Studio", "PERSONAL"),
    ("VLCC Wellness & Weight Loss", "PERSONAL"),
    ("Kaya Skin Clinic Laser Care", "PERSONAL"),
    ("Bodycraft Salon & Spa Therapy", "PERSONAL"),
    ("Cult.fit Fitness Center Gym", "PERSONAL"),
    ("Gold Gym Fitness Membership", "PERSONAL"),
    ("Anytime Fitness 24/7 Gym", "PERSONAL"),
    ("Oddissey Mens Salon Grooming", "PERSONAL"),
    ("Ayurvedic Massage Therapy Spa", "PERSONAL"),
    ("O2 Spa Terminal Relaxation", "PERSONAL"),
    ("Tattoo Studio Ink Parlour", "PERSONAL"),
    ("Nail Art Studio Pedicure Care", "PERSONAL"),

    # TRANSFERS (P2P UPI Transfers, IMPS/NEFT, Person-to-Person Payments)
    ("Sent Rs to Chidambaram via UPI", "TRANSFERS"),
    ("Sent Rs to Shreya B Shetty via UPI", "TRANSFERS"),
    ("Sent Rs to Kavitha P on UPI", "TRANSFERS"),
    ("Sent Rs to Thangarasu on UPI", "TRANSFERS"),
    ("Sent Rs to Kalashetty S N", "TRANSFERS"),
    ("Sent Rs to Divya G via PhonePe", "TRANSFERS"),
    ("Sent Rs to Srinivasa KS via GPay", "TRANSFERS"),
    ("Sent Rs to R Raghupathi UPI", "TRANSFERS"),
    ("Sent Rs to Munna Rafeeq S", "TRANSFERS"),
    ("Sent Rs to Krishnan T via UPI", "TRANSFERS"),
    ("Sent Rs to R Magesh on HDFC", "TRANSFERS"),
    ("Sent Rs to Muniyan Ethiraj", "TRANSFERS"),
    ("Sent Rs to Tammannappa via UPI", "TRANSFERS"),
    ("Sent Rs to Tamilarasi via UPI", "TRANSFERS"),
    ("Sent Rs to Tamilselvi S", "TRANSFERS"),
    ("Sent Rs to Tharunmadhes Y", "TRANSFERS"),
    ("Sent Rs to Theagarajan V", "TRANSFERS"),
    ("Sent Rs to P Santhoshkumar", "TRANSFERS"),
    ("Sent Rs to P Vadivelu via UPI", "TRANSFERS"),
    ("Sent Rs to P Vasugi via UPI", "TRANSFERS"),
    ("Sent Rs to Pramila P on UPI", "TRANSFERS"),
    ("Sent Rs to Prasanth Kitturaj", "TRANSFERS"),
    ("Sent Rs to R Kannan on UPI", "TRANSFERS"),
    ("Sent Rs to R Vijayalakshmi", "TRANSFERS"),
    ("Sent Rs to Rahul R via UPI", "TRANSFERS"),
    ("Sent Rs to Rajani M on UPI", "TRANSFERS"),
    ("Sent Rs to Rajivgandhi on UPI", "TRANSFERS"),
    ("Sent Rs to Rajkamal Ashokan", "TRANSFERS"),
    ("Sent Rs to Rajkumar S via UPI", "TRANSFERS"),
    ("Sent Rs to S Arunachalam UPI", "TRANSFERS"),
    ("Sent Rs to S Valarmathy via UPI", "TRANSFERS"),
    ("Sent Rs to Saikumar Man on UPI", "TRANSFERS"),
    ("Sent Rs to Sakthimani via UPI", "TRANSFERS"),
    ("Sent Rs to Sakthivel M on UPI", "TRANSFERS"),
    ("Sent Rs to Sampath Kumar on UPI", "TRANSFERS"),
    ("Sent Rs to Sanjan Kumar Das", "TRANSFERS"),
    ("Sent Rs to Santhosh Jeevagar", "TRANSFERS"),
    ("Sent Rs to Santhosh P S on UPI", "TRANSFERS"),
    ("Sent Rs to Seethalakshmi UPI", "TRANSFERS"),
    ("Sent Rs to Selvarani S via UPI", "TRANSFERS"),
    ("Sent Rs to Shanmugapandi E", "TRANSFERS"),
    ("Sent Rs to Shri A Ravi via UPI", "TRANSFERS"),
    ("Sent Rs to Sivanarayanan R", "TRANSFERS"),
    ("Sent Rs to Sivapalan R via UPI", "TRANSFERS"),
    ("Sent Rs to SK Abbas on UPI", "TRANSFERS"),
    ("Sent Rs to Sk Safiulla via UPI", "TRANSFERS"),
    ("Sent Rs to Solairaj N on UPI", "TRANSFERS"),
    ("Sent Rs to Soundaram via UPI", "TRANSFERS"),
    ("Sent Rs to Sundararajan G", "TRANSFERS"),
    ("Sent Rs to Syedshahnawaz on UPI", "TRANSFERS"),
    ("Sent Rs to Sathish A on UPI", "TRANSFERS"),
    ("Sent Rs to Sathya Mathews S", "TRANSFERS"),
    ("Sent Rs to Sikkandar Sulthan I", "TRANSFERS"),
    ("Sent Rs to Tajmulkhan on UPI", "TRANSFERS"),
    ("Sent Rs to V Ravikumar on UPI", "TRANSFERS"),
    ("Sent Rs to Valli V via UPI", "TRANSFERS"),
    ("Sent Rs to Vasudevan B on UPI", "TRANSFERS"),
    ("Sent Rs to Velmurugan R on UPI", "TRANSFERS"),
    ("Sent Rs to Vignesh M on UPI", "TRANSFERS"),
    ("Sent Rs to Vijay Kumar J on UPI", "TRANSFERS"),
    ("Sent Rs to Vimaldev on UPI", "TRANSFERS"),
    ("Sent Rs to Zahara Begum on UPI", "TRANSFERS"),
    ("Sent via UPI to jaswanth27@okaxis", "TRANSFERS"),
    ("Sent via UPI to karthikgn@okaxis", "TRANSFERS"),
    ("Sent via UPI to manjuladevi@okaxis", "TRANSFERS"),
    ("Sent via UPI to mohannataraj@okaxis", "TRANSFERS"),
    ("Sent via UPI to parthiban@okaxis", "TRANSFERS"),
    ("Sent via UPI to sakthivel@okaxis", "TRANSFERS"),
    ("Sent via UPI to sasiguru@ptyes", "TRANSFERS"),
    ("Transfer to Own Savings Account", "TRANSFERS"),
    ("IMPS P2P Outward Fund Transfer", "TRANSFERS"),
    ("NEFT Fund Transfer to Beneficiary", "TRANSFERS"),

    # FEES_CHARGES (Bank Charges, Surcharges, Penalty Fees)
    ("Annual Credit Card Maintenance Fee", "FEES_CHARGES"),
    ("ATM Cash Withdrawal Charges", "FEES_CHARGES"),
    ("Bank SMS Alert Service Charges", "FEES_CHARGES"),
    ("Late Payment Surcharge Fee", "FEES_CHARGES"),
    ("Debit Card Annual Fee Renewal", "FEES_CHARGES"),
    ("Non Maintenance Minimum Balance Penalty", "FEES_CHARGES"),
    ("Cheque Bounce Charges Penalty", "FEES_CHARGES"),
    ("Forex Markup Currency Conversion Fee", "FEES_CHARGES"),
    ("GST on Banking Service Charges", "FEES_CHARGES"),
    ("ECS Mandate Return Fee", "FEES_CHARGES"),

    # EDUCATION (Schools, Colleges, Academies, Tuition, Online Courses)
    ("Lakshara Academy Tuition Classes", "EDUCATION"),
    ("Kendriya Vidyalaya School Fees", "EDUCATION"),
    ("Brilliant Coaching Center NEET", "EDUCATION"),
    ("College Semester Tuition Fees", "EDUCATION"),
    ("Allen Career Institute Coaching", "EDUCATION"),
    ("Aakash Educational Services JEE", "EDUCATION"),
    ("FIITJEE Entrance Coaching Classes", "EDUCATION"),
    ("Physics Wallah Learning App", "EDUCATION"),
    ("Unacademy Plus Subscription", "EDUCATION"),
    ("Coursera Learning Certificate", "EDUCATION"),
    ("Udemy Online Course Purchase", "EDUCATION"),

    # SALARY_INCOME (Salary, Payroll, Consulting, Dividends)
    ("Monthly Salary Credit from Employer", "SALARY_INCOME"),
    ("Salary credited for August 2026", "SALARY_INCOME"),
    ("Consulting Fee Income Received", "SALARY_INCOME"),
    ("Freelance Project Payment Received", "SALARY_INCOME"),
    ("Annual Performance Bonus Payout", "SALARY_INCOME"),
    ("Internship Stipend Credit Amount", "SALARY_INCOME"),
    ("Dividend Payout from Tata Consultancy", "SALARY_INCOME"),
    ("Interest Credited on Fixed Deposit", "SALARY_INCOME"),

    # OTHERS (Miscellaneous unclassified vendors)
    ("Miscellaneous Expense Payment", "OTHERS"),
    ("General Vendor Settlement", "OTHERS"),
    ("Unclassified Store Outlet", "OTHERS"),
    ("Misc Payment Service Provider", "OTHERS")
]


def clean_text(text: str) -> str:
    """Lowercase and strip special characters, leaving clean tokens."""
    t = text.lower()
    t = re.sub(r"[^a-z0-9\s]", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t


def train_and_export():
    print(f"Training on {len(DATASET)} diverse Indian merchant and transaction samples across 14 categories...")

    texts = [clean_text(x[0]) for x in DATASET]
    labels = [x[1] for x in DATASET]

    label_to_idx = {cat: i for i, cat in enumerate(CATEGORIES)}
    y = np.array([label_to_idx[l] for l in labels])

    # Combine word n-grams (1-2 words) and character subword n-grams (3-4 chars)
    word_vectorizer = TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=1,
        max_features=2500,
        sublinear_tf=True
    )

    char_vectorizer = TfidfVectorizer(
        analyzer="char_wb",
        ngram_range=(3, 4),
        min_df=1,
        max_features=3000,
        sublinear_tf=True
    )

    feature_union = FeatureUnion([
        ("word", word_vectorizer),
        ("char", char_vectorizer)
    ])

    X = feature_union.fit_transform(texts)

    # Train multinomial logistic regression with L2 regularization
    clf = LogisticRegression(
        C=3.0,
        max_iter=1000,
        solver="lbfgs",
        class_weight="balanced",
        random_state=42
    )
    clf.fit(X, y)

    # Export vocabulary and IDF weights
    word_vocab = {str(k): int(v) for k, v in word_vectorizer.vocabulary_.items()}
    word_idf = [float(x) for x in word_vectorizer.idf_.tolist()]
    char_vocab = {str(k): int(v) for k, v in char_vectorizer.vocabulary_.items()}
    char_idf = [float(x) for x in char_vectorizer.idf_.tolist()]

    # Coefficients shape: (n_classes, n_features)
    # Intercept shape: (n_classes,)
    weights = [[float(c) for c in row] for row in clf.coef_.tolist()]
    intercept = [float(b) for b in clf.intercept_.tolist()]

    clf_classes = [CATEGORIES[int(i)] for i in clf.classes_]

    model_payload = {
        "categories": clf_classes,
        "word_vocab": word_vocab,
        "word_idf": word_idf,
        "char_vocab": char_vocab,
        "char_idf": char_idf,
        "weights": weights,
        "intercept": intercept
    }

    output_path = os.path.join("app", "src", "main", "assets", "models", "merchant_classifier_weights.json")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(model_payload, f, separators=(",", ":"))

    size_kb = os.path.getsize(output_path) / 1024
    print(f"Model successfully trained & exported to {output_path} ({size_kb:.2f} KB)")


if __name__ == "__main__":
    train_and_export()
